development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://flix-chillpubserver.com/faye"
  secret_token: "e76ffa69b86917494e6ef42c1f15cd0e287f79ee9b40e3ae64995241d5acfcbc"
  signature_expiration: 28800 # eight hours
